### PRIMERA PRACTICA

In [ ]:
print ("Hola papu")

Hola papu


--------------------------------------------------------------------------------

### MI BIBLIOGRAFÍA

Me llamo Digeo Castro Jurado, Tengo 21 años, me gustan las mujeres y me gustra minecraft

1. Tengo dos gatos 🐈
2. Tengo tatuajes
3. Me gusta el ramen
4. Me gusta el equipo del Barcelona
5. Me gusta los videojuegos

__A veces me pongo a reflexionar sobre la vida en el baño, ya que a veces dudo de mi existencia. ¿Por qué vivimos?, ¿Para qué nacemos?, ¿Para que nací?, ¿Cuál es mi importancia en esta sociedad?__

Una de mis frases favoritas es:

### _MEJOR A DENTRO QUE A FUERA_

Esta frase me la dijo mi papá que desaparecio cuando fue por cigarros, sin duda un gran padre, de el aprendi muchas cosas como que debo de ser el hombre de la casa, respetar a las mujeres y siempre consolaras ya que yo soy un rogon. ese tiempo pero pues no paso nada, ni di mi primer beso. Fue durantre la preparatoria cuando paso todo, conoci un amor (me engaño) di mi primer beso y conoci a varias amistades muy buenas, pero como todo inicio bonito debe tener una historia debe tener un final horrible, ya que llego la pademia y mi vida se arruino ya que me dio ansiedad al estar encerrado durante mas de 3 años ya que tampoco pase el examen de admisión y pues durante mucho tiempo no sali a casa pero ya que poco a poco sali y llegar y así fue como llegue a la universidad, donde despues de varios intentos en querer entrar a la universidad en un momento elegí el CUI por amigos y familiares despues de todo lo que paso en mi vida ya es momento de seguir adelante en esta nueva etapa de mi vida.

Mi canción favorita es: [Mira este video en YouTube](https://www.youtube.com/watch?v=HLetFEpgPgY)


| Tipo       | Ejemplo de Pokémon       | Ventaja contra                | Débil contra                   |
|------------|--------------------------|--------------------------------|--------------------------------|
| Normal     | Snorlax                  | Ninguno en especial            | Lucha                          |
| Fuego      | Charizard                | Planta, Bicho, Hielo, Acero    | Agua, Tierra, Roca             |
| Agua       | Blastoise                | Fuego, Tierra, Roca            | Planta, Eléctrico              |
| Planta     | Venusaur                 | Agua, Tierra, Roca             | Fuego, Hielo, Veneno, Volador, Bicho |
| Eléctrico  | Pikachu                  | Agua, Volador                  | Tierra                         |
| Hielo      | Articuno                 | Planta, Tierra, Volador, Dragón| Fuego, Lucha, Roca, Acero      |
| Lucha      | Machamp                  | Normal, Hielo, Roca, Siniestro, Acero | Volador, Psíquico, Hada   |
| Veneno     | Gengar                   | Planta, Hada                   | Tierra, Psíquico               |
| Tierra     | Garchomp                 | Fuego, Eléctrico, Veneno, Roca, Acero | Agua, Planta, Hielo        |
| Volador    | Pidgeot                  | Planta, Lucha, Bicho           | Eléctrico, Hielo, Roca         |
| Psíquico   | Mewtwo                   | Lucha, Veneno                  | Bicho, Fantasma, Siniestro     |
| Bicho      | Scyther                  | Planta, Psíquico, Siniestro    | Fuego, Volador, Roca           |
| Roca       | Onix                     | Fuego, Hielo, Volador, Bicho   | Agua, Planta, Lucha, Tierra, Acero |
| Fantasma   | Gengar                   | Psíquico, Fantasma             | Fantasma, Siniestro            |
| Dragón     | Dragonite                | Dragón                         | Hielo, Dragón, Hada            |
| Siniestro  | Umbreon                  | Psíquico, Fantasma             | Lucha, Bicho, Hada             |
| Acero      | Metagross                | Hielo, Roca, Hada              | Fuego, Lucha, Tierra           |
| Hada       | Sylveon                  | Lucha, Dragón, Siniestro       | Veneno, Acero                  |

<span style="color:blue">
Me gusta mucho los videojuegos actualmente aunque juego solo dos que son Rainbow Six y Hollow Knight: Silksong, me gusta jugar mucho videojuegos, mis juegos favoritos son Minecraft, Ark, Hollow Knight, Valorant entre otros. Sin duda soy un friki de los videojuegos ya que me agrada demasiado.
</span>


- [ ] Tarea terminada
- [x] Tarea pendiente

![Logo de GitHub](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Toluca_a_los_pies_del_nevado.jpg/1920px-Toluca_a_los_pies_del_nevado.jpg)



*itálica*  _itálica_
**negrita**  __negrita__
~~tachado~~
`código_en_línea`
> “Cita breve en línea”

# CODIGOS BASICOS DE PYTHOM  

### USO DE LIBRERIAS EN PYTHON


In [ ]:
import math
import random
from datetime import date

raiz_144 = math.sqrt(144)          # raíz cuadrada

print("Raíz de 144:", raiz_144)

Raíz de 144: 12.0


EJEMPLO Y EXPLICACIÓN

In [ ]:
import math
import random
from datetime import date

# 1. FUNCIONES MATEMÁTICAS BÁSICAS
numero = 25
raiz_cuadrada = math.sqrt(numero)          # Raíz cuadrada
potencia = math.pow(5, 3)                  # 5 elevado a 3
logaritmo = math.log(100)                  # Logaritmo natural

print(f"Raíz cuadrada de {numero}: {raiz_cuadrada}")
print(f"5 elevado a 3: {potencia}")
print(f"Logaritmo natural de 100: {logaritmo:.2f}")

Raíz cuadrada de 25: 5.0
5 elevado a 3: 125.0
Logaritmo natural de 100: 4.61


Importamos la librería math para tener herramientas matemáticas

Usamos math.sqrt(144) para calcular la raíz cuadrada de 144

Guardamos el resultado en la variable raiz_144

Imprimimos el resultado mostrando "Raíz de 144: 12.0"

En esencia: Python ya trae la fórmula de la raíz cuadrada programada, nosotros solo la usamos cuando la necesitamos.

### VARIABLES Y TIPOS DE DATOS


In [ ]:
nombre = "María"        # str
edad = 17               # int
altura_m = 1.65         # float
estudiante = True       # bool
materias = ["Mate", "Fis", "Prog"]  # list
coordenadas = (19.4, -99.1)         # tuple
unicos = {1, 2, 2, 3}               # set (sin duplicados)
perfil = {"usuario": "maria17", "pais": "MX"}  # dict

print(nombre, type(nombre))
print(edad, type(edad))
print(altura_m, type(altura_m))
print(estudiante, type(estudiante))
print(materias, type(materias))
print(coordenadas, type(coordenadas))
print(unicos, type(unicos))
print(perfil, type(perfil))

María <class 'str'>
17 <class 'int'>
1.65 <class 'float'>
True <class 'bool'>
['Mate', 'Fis', 'Prog'] <class 'list'>
(19.4, -99.1) <class 'tuple'>
{1, 2, 3} <class 'set'>
{'usuario': 'maria17', 'pais': 'MX'} <class 'dict'>


EJEMPLO Y EXPLICACIÓN

In [ ]:
# Diferentes tipos de datos en Python
producto = "Laptop"            # Texto (str)
precio = 899.99                # Decimal (float)
stock = 15                     # Entero (int)
disponible = True              # Booleano (bool)
caracteristicas = ["8GB RAM", "256GB SSD", "Intel i5"]  # Lista

print("Producto:", producto, type(producto))
print("Precio:", precio, type(precio))
print("En stock:", stock, type(stock))
print("Disponible:", disponible, type(disponible))
print("Características:", caracteristicas, type(caracteristicas))

thon tiene varios tipos de datos para diferentes usos:

str → Texto y palabras

int → Números enteros

float → Números con decimales

bool → Valores True/False (verdadero/falso)

list → Listas de elementos ordenados

### ENTRADA/SALIDA Y CONVERSIONES

In [ ]:
# Ejemplo sin input (simulamos datos)
a_texto = "12.5"
b_texto = "3"

a = float(a_texto)  # 12.5
b = int(b_texto)    # 3

suma = a + b
division = a / b

print(f"a={a} (float), b={b} (int) -> suma={suma}, división={division:.2f}")

a=12.5 (float), b=3 (int) -> suma=15.5, división=4.17


EJEMPLO Y EXPLICACIÓN

In [ ]:
# Convertimos texto a números y hacemos operaciones
precio_texto = "99.90"
cantidad_texto = "2"

precio = float(precio_texto)    # Convertir a decimal
cantidad = int(cantidad_texto)  # Convertir a entero

total = precio * cantidad
descuento = total * 0.10

print(f"Precio: ${precio}")
print(f"Cantidad: {cantidad}")
print(f"Total: ${total:.2f}")
print(f"Descuento (10%): ${descuento:.2f}")

La conversión de tipos nos permite:

float(texto) → Convierte texto a número decimal

int(texto) → Convierte texto a número entero

str(numero) → Convierte número a texto

¿Por qué es útil?
Porque los datos que vienen de archivos o usuarios siempre son texto, pero para hacer operaciones matemáticas necesitamos convertirlos a números.

### OPERACIONES Y EXPRESIONES

In [ ]:
print("2 + 3 * 4 =", 2 + 3 * 4)           # 14
print("(2 + 3) * 4 =", (2 + 3) * 4)       # 20
print("7 // 3 =", 7 // 3, " 7 % 3 =", 7 % 3)  # 2 y 1
print("2 ** 3 ** 2 =", 2 ** 3 ** 2)       # 2 ** (3**2) = 2 ** 9 = 512

# Lógicos: aprobar si promedio>=7 y asistencia>=0.8
promedio, asistencia = 7.2, 0.85
aprueba = (promedio >= 7) and (asistencia >= 0.8)
print("¿Aprueba?", aprueba)

2 + 3 * 4 = 14
(2 + 3) * 4 = 20
7 // 3 = 2  7 % 3 = 1
2 ** 3 ** 2 = 512
¿Aprueba? True


EJEMPLO Y EXPLICACIÓN

In [ ]:
# Operaciones matemáticas y lógicas
print("10 - 2 * 3 =", 10 - 2 * 3)           # 10 - 6 = 4
print("(10 - 2) * 3 =", (10 - 2) * 3)       # 8 * 3 = 24
print("15 // 4 =", 15 // 4, " 15 % 4 =", 15 % 4)  # 3 y 3
print("3 ** 2 ** 2 =", 3 ** 2 ** 2)         # 3 ** (2**2) = 3 ** 4 = 81

# Lógicos: acceso si es mayor de edad y tiene ticket
edad = 18
tiene_ticket = True
acceso_permitido = (edad >= 18) and tiene_ticket
print("¿Acceso permitido?", acceso_permitido)

* Multiplicación → Tiene prioridad sobre + y -

() Paréntesis → Cambian el orden de las operaciones

// División entera → Resultado sin decimales

% Módulo → Residuo de una división

** Potencia → Se calcula de derecha a izquierda

and Y lógico → Ambas condiciones deben ser True

Regla clave: Python sigue el orden matemático: paréntesis → potencias → multiplicación/división → suma/resta.


### CADENAS (STRINGS)

In [ ]:
# Limpieza y formateo
s = "   Python ES Genial  "
limpia = s.strip().lower().replace("genial", "fantástico")
palabras = limpia.split()

print("Original:", repr(s))
print("Limpia:", limpia)
print("Palabras:", palabras)

# Pequeña utilidad: detectar palíndromos (ignorando espacios y mayúsculas)
def es_palindromo(texto: str) -> bool:
    t = "".join(ch.lower() for ch in texto if ch.isalnum())
    return t == t[::-1]

print("¿Anita lava la tina es palíndromo?", es_palindromo("Anita lava la tina"))
print("¿Hola mundo es palíndromo?", es_palindromo("Hola mundo"))

Original: '   Python ES Genial  '
Limpia: python es fantástico
Palabras: ['python', 'es', 'fantástico']
¿Anita lava la tina es palíndromo? True
¿Hola mundo es palíndromo? False


EJEMPLO Y EXPLICACIÓN

In [ ]:
# Limpieza y formateo de texto
texto_original = "   Hola MUNDO de Python  "
texto_limpio = texto_original.strip().lower().replace("python", "programación")
palabras = texto_limpio.split()

print("Original:", repr(texto_original))
print("Limpio:", texto_limpio)
print("Palabras:", palabras)

# Función para verificar si una palabra es palíndromo
def es_palindromo(palabra: str) -> bool:
    palabra_limpia = palabra.lower().replace(" ", "")
    return palabra_limpia == palabra_limpia[::-1]

print("¿'reconocer' es palíndromo?", es_palindromo("reconocer"))
print("¿'casa' es palíndromo?", es_palindromo("casa"))

Original: '   Hola MUNDO de Python  '
Limpio: hola mundo de programación
Palabras: ['hola', 'mundo', 'de', 'programación']
¿'reconocer' es palíndromo? True
¿'casa' es palíndromo? False


Métodos útiles para texto:

strip() → Elimina espacios al inicio y final

lower() → Convierte todo a minúsculas

replace() → Cambia una palabra por otra

split() → Divide el texto en palabras

[::-1] → Invierte el texto (truco con slices)

Palíndromo: palabra que se lee igual al derecho y al revés (ej: "reconocer", "ana").

¿Cómo funciona? Limpiamos el texto, lo invertimos y comparamos si son iguales.

### CONTROL DE FLUJO: if, for, while

In [ ]:
# if + for: suma de cuadrados del 1 al 5
suma_cuad = 0
for n in range(1, 6):
    cuadrado = n * n
    if cuadrado % 2 == 0:
        pass  # no hacemos nada especial; es solo de ejemplo
    suma_cuad += cuadrado
print("Suma de cuadrados 1..5 =", suma_cuad)

# while: generar primeros 8 Fibonacci
fib = [0, 1]
while len(fib) < 8:
    fib.append(fib[-1] + fib[-2])
print("Fibonacci (8):", fib)

Suma de cuadrados 1..5 = 55
Fibonacci (8): [0, 1, 1, 2, 3, 5, 8, 13]


EJEMPLO Y EXPLICACIÓN

In [ ]:
# Suma de números pares del 1 al 10
suma_pares = 0
for numero in range(1, 11):
    if numero % 2 == 0:  # Si el número es par
        suma_pares += numero
print("Suma de números pares del 1 al 10 =", suma_pares)

# Generar números del 1 al 5 con while
contador = 1
numeros = []
while contador <= 5:
    numeros.append(contador)
    contador += 1
print("Números del 1 al 5:", numeros)

Suma de números pares del 1 al 10 = 30
Números del 1 al 5: [1, 2, 3, 4, 5]


For: Se usa cuando sabemos cuántas veces repetir

range(1, 11) → genera números del 1 al 10

if numero % 2 == 0 → verifica si es par

While: Se usa cuando no sabemos cuántas veces repetir

contador <= 5 → condición para seguir repitiendo

contador += 1 → aumenta el contador en cada ciclo

Diferencia clave:

For → Para recorrer listas o rangos conocidos

While → Para repetir mientras una condición sea verdadera

### COLECCIONES: LISTAS, TUPLAS, CONJUNTOS, DIRECCIONARIOS

In [ ]:
# Lista
compras = ["pan", "leche", "huevo", "arroz"]
compras.append("manzana")
compras.remove("pan")
compras.sort()
print("Lista compras:", compras, " ¿leche?", "leche" in compras)

# Tupla
punto = (3, 4)
print("Tupla punto:", punto)

# Conjunto (quita duplicados)
nums = [1, 2, 2, 3, 3, 3]
unicos = set(nums)
print("Únicos:", unicos)

# Diccionario
calif = {"Ana": [9, 8, 10], "Luis": [7, 7, 8]}
prom_ana = sum(calif["Ana"]) / len(calif["Ana"])
prom_grupo = sum(sum(v) for v in calif.values()) / sum(len(v) for v in calif.values())
print("Promedio Ana:", prom_ana, "Promedio grupo:", round(prom_grupo, 2))

Lista compras: ['arroz', 'huevo', 'leche', 'manzana']  ¿leche? True
Tupla punto: (3, 4)
Únicos: {1, 2, 3}
Promedio Ana: 9.0 Promedio grupo: 8.17


EJEMPLO Y EXPLICACIÓN

In [ ]:
# Lista de frutas
frutas = ["manzana", "banana", "naranja"]
frutas.append("uva")          # Agregar al final
frutas.remove("banana")       # Quitar elemento
frutas.sort()                 # Ordenar alfabéticamente
print("Frutas:", frutas)
print("¿Hay manzana?", "manzana" in frutas)

# Tupla de coordenadas (inmutable)
coordenada = (10, 20)
print("Coordenada:", coordenada)

# Conjunto para eliminar duplicados
numeros = [5, 3, 5, 2, 3, 1]
sin_duplicados = set(numeros)
print("Números únicos:", sin_duplicados)

# Diccionario de edades
edades = {"Ana": 25, "Carlos": 30, "Maria": 28}
promedio_edades = sum(edades.values()) / len(edades)
print("Edad promedio:", round(promedio_edades, 1))

Lista: Colección ordenada y modificable

append() → agregar elemento

remove() → quitar elemento

sort() → ordenar

in → verificar si existe

Tupla: Colección ordenada e INMODIFICABLE

Útil para datos constantes

Conjunto (Set): Colección NO ordenada sin duplicados

Elimina automáticamente repetidos

Diccionario: Pares clave-valor

valores() → obtiene todos los valores

Claves únicas como índices

### COMPRENSIONES (LISTAS, SETS Y ADICCIONARIOS)

In [ ]:
# Lista de cuadrados y filtrado de pares
cuadrados = [n*n for n in range(1, 11)]
pares = [x for x in cuadrados if x % 2 == 0]
print("Cuadrados:", cuadrados)
print("Pares:", pares)

# Diccionario inverso (materia -> profe) => (profe -> materia)
materia_a_profe = {"Mate": "Sofía", "Física": "Sofía", "Historia": "Carlos"}
# Si un profe repite, guardamos una sola materia (ejemplo simple)
profe_a_materia = {profe: materia for materia, profe in materia_a_profe.items()}
print("Inverso simple:", profe_a_materia)

# Set comprehension: letras únicas sin vocales
s = "programación"
sin_vocales = {c for c in s if c not in "aeiouáéíóú"}
print("Letras sin vocales:", sin_vocales)

EJEMPLO Y EXPLICACIÓN

In [ ]:
# Lista de números al cuadrado
numeros = [1, 2, 3, 4, 5]
cuadrados = [n * n for n in numeros]
print("Cuadrados:", cuadrados)

# Números pares solamente
pares = [n for n in numeros if n % 2 == 0]
print("Pares:", pares)

# Diccionario de precios con descuento
precios = {"pan": 10, "leche": 20, "huevo": 15}
descuento = {producto: precio * 0.9 for producto, precio in precios.items()}
print("Precios con 10% descuento:", descuento)

# Letras únicas de una palabra (sin duplicados)
palabra = "python"
letras_unicas = {letra for letra in palabra}
print("Letras únicas:", letras_unicas)

Comprensión de listas: Crear listas de forma rápida

[n * n for n in numeros] → cada número al cuadrado

[n for n in numeros if n % 2 == 0] → solo números pares

Comprensión de diccionarios: Transformar diccionarios

{producto: precio * 0.9 for producto, precio in precios.items()} → aplicar descuento

Comprensión de conjuntos: Crear conjuntos sin duplicados

{letra for letra in palabra} → letras únicas de una palabra

Ventaja: Código más corto, legible y eficiente que usar bucles tradicionales.



### FUNCIONES (def)

In [ ]:
def area_rectangulo(base: float, altura: float = 1.0) -> float:
    """Calcula el área de un rectángulo."""
    return base * altura

def es_segura(pw: str) -> bool:
    """Contraseña segura: >=8 y contiene mayúscula, minúscula y dígito."""
    return (
        len(pw) >= 8 and
        any(c.isupper() for c in pw) and
        any(c.islower() for c in pw) and
        any(c.isdigit() for c in pw)
    )

print("Área 5x2 =", area_rectangulo(5, 2))
print("¿'Hola1234' es segura?", es_segura("Hola1234"))
print("¿'hola' es segura?", es_segura("hola"))

EJEMPLO Y EXPLICACIÓN

In [ ]:
def calcular_iva(precio: float, iva: float = 0.16) -> float:
    """Calcula el IVA de un producto."""
    return precio * iva

def es_valido_email(email: str) -> bool:
    """Verifica si un email tiene formato válido (simple)."""
    return (
        "@" in email and
        "." in email and
        len(email) >= 5
    )

print("IVA de $100:", calcular_iva(100))
print("IVA de $200 con 10%:", calcular_iva(200, 0.10))
print("¿'usuario@mail.com' es válido?", es_valido_email("usuario@mail.com"))
print("¿'hola' es válido?", es_valido_email("hola"))

Funciones: Bloques de código reutilizables

Parámetros: Datos que recibe la función (precio, iva)

Parámetro opcional: iva=0.16 → valor por defecto

Tipo de datos: : float → indica el tipo que espera

Docstring: """explicación""" → documenta la función

Return: return → devuelve el resultado

Ventajas:

Reutilizar código → escribir una vez, usar muchas

Organizar → divide el programa en partes pequeñas

Más legible → nombres claros para cada acción

### MÓDULOS Y PAQUETES

In [ ]:
# Creamos un módulo sencillo llamado utilidades.py
contenido = '''
def limpiar_texto(s: str) -> str:
    return s.strip().lower()

def contar_vocales(s: str) -> dict:
    s = s.lower()
    vocs = "aeiouáéíóú"
    return {v: s.count(v) for v in vocs if s.count(v) > 0}
'''.lstrip()

with open("utilidades.py", "w", encoding="utf-8") as f:
    f.write(contenido)

# Lo importamos y usamos
import utilidades as ut

frase = "  HOLA Mundo, Programación en PYTHON  "
print("Limpia:", ut.limpiar_texto(frase))
print("Vocales:", ut.contar_vocales(frase))

EJEMPLO Y EXPLICACIÓN

In [ ]:
# Creamos un módulo matemático básico
contenido = '''
def sumar(a: float, b: float) -> float:
    """Suma dos números."""
    return a + b

def es_par(n: int) -> bool:
    """Verifica si un número es par."""
    return n % 2 == 0
'''.lstrip()

# Guardamos el módulo
with open("mates.py", "w", encoding="utf-8") as f:
    f.write(contenido)

# Importamos y usamos el módulo
import mates as mt

print("Suma 5 + 3:", mt.sumar(5, 3))
print("¿El 8 es par?", mt.es_par(8))
print("¿El 7 es par?", mt.es_par(7))

Pasos:

Crear módulo → Archivo .py con funciones

Guardar → with open("mates.py", "w")

Importar → import mates as mt

Usar → mt.sumar(5, 3)

Ventajas:

Organizar código → Dividir en archivos separados

Reutilizar → Usar las mismas funciones en diferentes programas

Mantenimiento → Más fácil de corregir y mejorar

Nota: Los módulos permiten tener código ordenado y profesional.



### ARCHIVOS: LEER Y ESCRIBIR

In [ ]:
# Guardamos y leemos notas, luego calculamos promedio
notas = [9.5, 8.0, 7.5, 10.0, 8.5]
with open("notas.txt", "w", encoding="utf-8") as f:
    for n in notas:
        f.write(f"{n}\n")

leidas = []
with open("notas.txt", "r", encoding="utf-8") as f:
    for linea in f:
        leidas.append(float(linea.strip()))

promedio = sum(leidas) / len(leidas)
print("Notas leídas:", leidas, " Promedio:", round(promedio, 2))

# Mini contador de palabras (simple)
texto = "¡Hola, hola! Esto es una prueba. Prueba simple; hola."
with open("texto.txt", "w", encoding="utf-8") as f:
    f.write(texto)

import re
with open("texto.txt", "r", encoding="utf-8") as f:
    contenido = f.read().lower()
    contenido = re.sub(r"[^a-záéíóúñü\s]", " ", contenido)  # quita signos
    palabras = [p for p in contenido.split() if p]

from collections import Counter
top5 = Counter(palabras).most_common(5)
print("Top 5 palabras:", top5)

EJEMPLO Y EXPLICACIÓN

In [ ]:
# Guardar y leer números favoritos
numeros = [7, 15, 23, 42, 5]
with open("favoritos.txt", "w", encoding="utf-8") as archivo:
    for num in numeros:
        archivo.write(f"{num}\n")

# Leer los números guardados
leidos = []
with open("favoritos.txt", "r", encoding="utf-8") as archivo:
    for linea in archivo:
        leidos.append(int(linea.strip()))

promedio = sum(leidos) / len(leidos)
print("Números leídos:", leidos)
print("Promedio:", round(promedio, 1))

# Contar palabras simples
texto = "Python es genial. Python es fácil. Me gusta Python."
with open("texto.txt", "w", encoding="utf-8") as archivo:
    archivo.write(texto)

# Leer y contar palabras
with open("texto.txt", "r", encoding="utf-8") as archivo:
    contenido = archivo.read().lower()
    palabras = contenido.replace(".", "").split()

from collections import Counter
conteo = Counter(palabras)
print("Palabra más común:", conteo.most_common(1))

Archivos:

Escribir: with open("archivo.txt", "w") → crea/sobrescribe

Leer: with open("archivo.txt", "r") → lee contenido

strip() → elimina espacios y saltos de línea

split() → divide texto en palabras

Counter: Cuenta elementos automáticamente

most_common(3) → las 3 palabras más repetidas

Ventajas:

Guardar datos → persistencia entre ejecuciones

Intercambiar información → entre programas

Procesar texto → análisis de contenido



### ERRORES Y EXEPCIONES

In [ ]:
def dividir_seguro(a, b):
    if b == 0:
        raise ValueError("No se puede dividir entre cero.")
    return a / b

# Ejemplos con manejo de excepciones
casos = [(10, 2), (5, 0), ("9", 3)]
for x, y in casos:
    try:
        resultado = dividir_seguro(x, y)
    except TypeError as e:
        print(f"TypeError con ({x}, {y}): {e}")
    except ValueError as e:
        print(f"ValueError con ({x}, {y}): {e}")
    else:
        print(f"{x} / {y} = {resultado}")
    finally:
        pass  # lugar para liberar recursos si fuera necesario

EJEMPLO Y EXPLICACIÓN

In [ ]:
def calcular_division(a, b):
    if b == 0:
        raise ValueError("Error: División por cero no permitida")
    return a / b

# Probamos diferentes casos
casos = [(10, 2), (5, 0), ("15", 3)]

for num1, num2 in casos:
    try:
        resultado = calcular_division(num1, num2)
    except TypeError:
        print(f"Error: '{num1}' no es un número válido")
    except ValueError as error:
        print(f"Error: {error}")
    else:
        print(f"{num1} ÷ {num2} = {resultado}")
    finally:
        print("--- Intento completado ---")

Manejo de errores:

try → Intenta ejecutar código que puede fallar

except → Atrapa y maneja errores específicos

else → Se ejecuta si NO hubo errores

finally → Siempre se ejecuta (útil para limpiar)

Tipos de errores comunes:

ValueError → Valor incorrecto (división por cero)

TypeError → Tipo de dato incorrecto

Ventajas:

Evita que el programa se cierre por errores

Da mensajes claros al usuario

Permite recuperarse de fallos